### ISSUE TITLE
linewidth is ignored

### ISSUE THREAD

**Issue by rrohwer** [mdhall272/ggarchery#2]
Hi, thanks for the neat package!

`geom_segment()` accepts a `linewidth=` argument, but it seems like `geom_arrowsegment` does not. Is this correct, and could it be added?

For context, I found your package while trying to make a "fat" arrow that does not extend past the provided coordinate limits.

Thanks!

Robin

**Comment by mdhall272** [comment]
Oh yeah, that's due to the rationalisation of the `linewidth` parameter that's gone into the most recent ggplot2. I will fix ASAP; the old `size` parameter will work in the interim, though.

**Comment by mdhall272** [comment]
It was a quick fix as it turns out; done.
